# Generated by Django 4.2.23 on 2025-09-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_ean_product_ean_carton_product_neta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='only_for_rent',
            field=models.BooleanField(default=False),
        ),
    ]
