# Generated by Django 4.2.23 on 2025-09-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_billing_address_order_billing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='different_delivery_address',
            field=models.BooleanField(default=False),
        ),
    ]
