# Generated by Django 4.2.23 on 2025-09-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_different_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
