# Generated by Django 4.2.23 on 2025-08-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_title', models.CharField(blank=True, default='', max_length=120)),
                ('hero_subtitle', models.CharField(blank=True, default='', max_length=240)),
                ('hero_button_text', models.CharField(blank=True, default='', max_length=60)),
                ('hero_button_url', models.CharField(blank=True, default='', max_length=200)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_title', models.CharField(blank=True, default='', max_length=120)),
                ('about_subtitle', models.CharField(blank=True, default='', max_length=240)),
                ('about_body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_order_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
