# Generated by Django 4.2.23 on 2025-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='webshop_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
