# Generated by Django 4.2.23 on 2025-09-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0002_sitecontent_webshop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='webshop_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
